version: "3"
services:
  hub:
     image: seleniarm/hub:4.10
     ports:
       - 4444:4444
  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=TRUE
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=TRUE
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  chrome-automation-test:
    image: mertcany/selenium
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - GRID_URL=hub
      - DATA_PROVIDER_THREAD_COUNT=2
      - THREAD_COUNT=1
      - TEST_SUITE=TestSuite.xml
    volumes:
      - ./output/chrome-automation-test:/home/selenium-grid/test-output
  firefox-automation-test:
    image: mertcany/selenium
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - GRID_URL=hub
      - DATA_PROVIDER_THREAD_COUNT=2
      - THREAD_COUNT=1
      - TEST_SUITE=TestSuite.xml
    volumes:
      - ./output/firefox-automation-test:/home/selenium-grid/test-output

